### ISSUE TITLE
a latest-url would be nice

### ISSUE THREAD

**Issue by divinity76** [moparisthebest/static-curl#1]
eg a 
```
https://github.com/moparisthebest/static-curl/blob/master/latest/curl-amd64
```
or something like that, always pointing to the latest release

**Comment by moparisthebest** [comment]
Does GitHub support something like this with their release URLs ?

**Comment by divinity76** [comment]
no i don't think so, the only way I've seen it done before is with binary blobs in the repo and linking to the "raw" repo link

**Comment by page-down** [comment]
Since the release files in this project have the same filename for each version, you can use the official GitHub link to download the latest version binary.

It is worth noting that for projects with version numbers inserted in the release filename, it is not possible to download them using the latest redirect url.

Please refer to 
https://docs.github.com/en/github/administering-a-repository/releasing-projects-on-github/linking-to-releases

```
https://github.com/moparisthebest/static-curl/releases/latest/download/curl-aarch64
https://github.com/moparisthebest/static-curl/releases/latest/download/curl-amd64
https://github.com/moparisthebest/static-curl/releases/latest/download/curl-armv7
https://github.com/moparisthebest/static-curl/releases/latest/download/curl-i386
https://github.com/moparisthebest/static-curl/releases/latest/download/curl-ppc64le
https://github.com/moparisthebest/static-curl/releases/latest/download/sha256sum.txt
https://github.com/moparisthebest/static-curl/releases/latest/download/sha256sum.txt.asc
```

**Comment by moparisthebest** [comment]
Thanks for the suggestion, this has been implemented.
